name: flame_game_network_1
description: network_1 Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.18.6
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
